### ISSUE TITLE
History Accordion UX

### ISSUE THREAD

**Issue by mugab686** [jburgos1/fls1lambdas#19]
**Steps to reproduce:**
1. Go to History > Awards accordion on the bottom  [Click here] (http://dev.floridalambdas.com/Florida-Sector-One-History.html)
2. Select any other year

**Expected:**
Only one year should be visible at a time. 

**Possible Solution:**
Load this page with all accordion items closed.

**Comment by jburgos1** [comment]
On the dev site it worked fine.

**Comment by jburgos1** [comment]
Fixed.
