### ISSUE TITLE
Scholarship application is not functional

### ISSUE THREAD

**Issue by mugab686** [jburgos1/fls1lambdas#20]
- [ ] The scholarship application needs to be added to the server
- [ ] Need to brand the application as well. 

@jburgos1, do you mind branding the application?  It's in our [Google drive](https://docs.google.com/document/d/1DLiD9kwgnzjeOQyUdb8jLn_D3xCobF1FNY4aKkHe32g/edit).

**Comment by jburgos1** [comment]
I can do that. I was thinking just a link to the pdf correct?

**Comment by jburgos1** [comment]
Done
