### ISSUE TITLE
Text color in dropdown menu items match the background in screen sizes below 767px 

### ISSUE THREAD

**Issue by mugab686** [jburgos1/fls1lambdas#23]
The text color is light brown on a darker brown background.  It turns white on hover, but it is unreadable when the dropdown is open. 

Whoever gets to it first can fix it.

**Comment by jburgos1** [comment]
Gonna need more info than that. What page, when? 

I'm pretty sure I have all header hovering/colors all fixed.

**Comment by jburgos1** [comment]
Unless you're running into merge conflicts in the css.

**Comment by mugab686** [comment]
Fixed.
